name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

services:
  postgresql:
    image: postgres:12-alpine
    env:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: postgres
      POSTGRES_DB: tower_troops_test
    options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    ports:
      - 5432:5432

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Rename .env.ci to .env.test
      run: mv .env.ci .env.test

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...
